server:
  port: 9296

spring:
  application:
    name: CLOUD-CONFIG
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Nikhil-Kudupudi/config-server
          clone-on-start: true